#!/bin/bash
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

function seek_and_project {
	kind=$1
	count=$(ls -1 . | grep ${kind} | wc -l)
	found_flag=false

	if [ "$count" -gt "1" ]; then
		echo "You have more then one ${kind} file. I'm not able to open your project/playground. Sorry!"
		exit
	fi

	for i in $(ls . | grep ${kind}); do
		found_flag=true
		project_file=${i}
	done

	if $found_flag; then
		current_tools_path=`xcode-select -p`
		contents_path=${current_tools_path%/*}
		xcode_app_path=${contents_path%/*}

		echo "Opening ${project_file}"
		open -a $xcode_app_path $project_file
		exit
	fi
}

seek_and_project ".xcworkspace"
seek_and_project ".xcodeproj"
seek_and_project ".playground"
seek_and_project ".swift"

if [ -f package.json ] && [ -d ios ]; then
	cd ios && echo "Seems to be a React-Native application"
	seek_and_project ".xcworkspace"
	seek_and_project ".xcodeproj"
fi

echo "There is no project/playground in this folder, buddy!"
